### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Anonymous-any** [TyKonKet/FS17_TowBar#6]
Hi good dev ! I hope my english is not so bad...
I just found your repositories and long time ago that I wanted to suggest this idea !
Linked to pull towbar, would you have the possibility to make a "cable winch" in same usage like the TajfunEGV80AHK for the wood (meaning on foot to attach you know), but of course it would look different like a winch for 4x4 as example, were it can be similar attach to towbar but for pulling as far distance because sometime they are not accessible with the towbar, or upside down or in water :/ I was think to 30-40 meters thinking to "TajfunEGV80AHK mod" will be fine to do the trick, a winch who could attach himself as well in front of as behind and but it would have both attach's like TajfunEGV80AHK for wood forest trees and attach's like tractor towbar for do not let the tractor get dragged/slidded you know ? and the best of all if it is possible to make it for Fs17 version(not obsolete to my viewpoint if you like this idea) argument too for this is Fs19 is lots buggy...sell, sell market.
My best regard TyKonKet thank for read time
Ano

**Comment by TyKonKet** [comment]
Hey, that's a good idea but unluckily, at the moment, I'm not modding anymore, I'm so sorry.

**Comment by Anonymous-any** [comment]
I must fix of what I was say because the player is floating it can't attach it from so far I think depending of the code. Also the vehicle can't restart after go out of water if I'm right from old FS BUT, it can be done for back out grain trailer from water when they are not empty because that happen when reset it to the shop then all grain is lost...
Thank so Daaaammmmmn :/ Regard

**Comment by Anonymous-any** [comment]
Hi hey it seem I have an alternative for FS19 were I'm going to try in few, but I'm continuing to wanted FS17 solution :)
https://github.com/Courseplay/courseplay/issues/3883#issuecomment-500258896
Not sure that can manualy attach a trailer !
Regard
